There are two main types of modding in Ground Branch: *non-asset based* (Quick Create) and *asset based* (Mod Kit / SDK), which are described in more detail below.

[NOTE]
--
The term '`asset`' has a particular meaning within the Unreal Engine 4. Any file which is viewable within the Unreal Engine content browser is an '`asset`'. With some limited exceptions (e.g. map files, .umap), Unreal Engine assets all have the .uasset file extension.
--

== Non-Asset Based Mods (Quick Create)

Non-asset based mods are manually assembled by the modder within a '`staged mod`' folder, and are packaged and uploaded within the game via the Modding->Quick Create menu.

With the exception of Mission files, non-asset files are readable and editable using external software, and often originate outside the game or SDK.
Examples of non-asset files include patch images, game mode scripts, localisation files, kit files of various kinds, and so on.
A Non-asset based mod may typically include several different types of files: for example, a game mode mod may additionally include missions for that game mode, localisation for the game mode, and custom AI kits.

The Quick Create system allows non-asset based mods to be made simply and quickly, and without having to download or use the Ground Branch Mod Kit / SDK.

=== Non asset mod basics

* link:/modding/quick-create[Quick Create menu]
* link:/modding/non-asset-file-types[List of non-asset file types]
* link:/modding/condensed-path-references[Non asset '`condensed`' filenames]

=== Game mode mods

* link:/modding/gamemode-modding[Game mode modding overview]
* link:/modding/mission-editor[Ground Branch Mission Editor guide]
* link:/modding/lua-api[Ground Branch Lua Library guide]

=== Patch mods

* link:/modding/patches[Patch modding overview]

== Asset Based Mods (Mod Kit / SDK)

include::modding/sdk/include-sdk-overview-and-links.adoc[]



