=== Overview of content types

You can create essentially any Unreal Engine content type that you want in the Mod Kit, but only some types will be '`auto recognised`' as part of inventory systems and suchlike.

A non-exhaustive list of content types is given below, with a link to a set of available '`master blueprints`' where applicable.
As described further in link:/modding/sdk/creating-child-assets[creating new game items], it is best to make your new mod content a child blueprint of a relevant master blueprint.

GROUND BRANCH uses particular asset types that are typically blueprints referencing '`fundamental`' UE4 types in various ways.
GROUND BRANCH asset types typically include a base c++ class and an implementing master blueprint (BP). If you don’t understand a word of this, that’s fine.

Unreal Engine has an asset registry which has defined (or allows you to define) specific '`asset types`'. The mean feature of the asset registry is that you can search for particular asset types and apply particular filters, and the asset registry will handle mapping the Unreal Engine asset reference to a specific file location.
The assets in mods can be added seamlessly to (and removed seamlessly from) the current list of assets.
This is handled by GROUND BRANCH and modders do not need to get involved with this process at all.
It should be noted that the term '`asset type`' is used in its specific technical meaning (within UE4) throughout this documentation.

=== Fundamental UE4 content types

This is a list of some fundamental UE4 asset types.
This list is very far from exhaustive.

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Asset type |Description |Notes
|Texture (.utx) |Image file |May be a UI element, an object skin, or other
|Material |Material |Typically uses a set of textures to define physical properties such as diffuse colour, specular, roughness and surface normal
|Material Instance |A material with a specific set of pre-defined parameters |Material and Material Instance are typically referenced in blueprints by a Material Interface (covers both)
|Static mesh |3D Model (static) |For level props and small attachments
|Skeletal mesh |3D Model (animated) |For characters, weapons, and kit and clothes applied to characters.
Maps to a predefined '`skeleton`' containing bones that can be controlled by animations
|Animation |A sequence of movements |Applies to bones of a particular skeleton, to animate skeletal meshes
|Animation montage |A predefined sequence of animations |Usually defines a particular action through a combination of individual animations
|Sound (.uax) |Sounds samples |Deprecated.
Use wwise instead
|Map |A collection of actors forming a game level |Maps are the geometry of a level, as distinct from mission objects which define the behaviour of game modes within the level
|===

A fundamental type of object missing from the above list (because it is not an asset as such) is a Blueprint (BP) class.
Blueprints combine components, properties and code in a visually accessible format.
They are a fundamental building block within Unreal Engine 4, usually providing a user-friendly access to underlying c++ classes, and simplify the creation of custom instances of classes.
We would refer you to generic Unreal Engine 4 documentation to learn more about blueprints.

Blueprints are not an asset type as such, but are typically used as the final embodiment of particular asset types.
That is to say, the vast majority of usable items in GROUND BRANCH are represented by a blueprint of the appropriate asset type.

=== GROUND BRANCH content types

These are currently supported GROUND BRANCH content types for modding; more exist but as of 1034 these are the officially supported ones.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Asset type |Description |Master blueprint(s) |Modding
|Primary |Primary weapon, e.g. rifle, shotgun, LMG, sniper rifle |link:/modding/sdk/master-bps-weapons[Primary master BP list] |link:/modding/sdk/weapon[Weapon modding]
|Sidearm |Sidearm, e.g. pistol |`+BP_Handgun_Master+` |link:/modding/sdk/weapon[Weapon modding]
|Magazine |Holds bullets |`+BP_Magazine_Master+` |link:/modding/sdk/magazine-modding[Magazine modding]
|===
